preload = $HOME/.wallpaper/12_PortalGood_1920x1080.png

wallpaper = , $HOME/.wallpaper/12_PortalGood_1920x1080.png

#preload = $HOME/.wallpaper/5_LesbianCatPile_3840x2160.png

#wallpaper = , $HOME/.wallpaper/5_LesbianCatPile_3840x2160.png
